### ISSUE TITLE
It it possible to reverse engineer database to generate ticdat schema and data object automaticly?

### ISSUE THREAD

**Issue by qtbhappy** [ticdat/ticdat#101]
It it possible to reverse engineer database to generate ticdat schema and data object automaticly?
We know that SqlAlchemy could do this.

**Comment by pjcpjc** [comment]
Do you have a link or example code explaining the SQLAlchemy functionality you're talking about? My understanding is OEM's really do require you to define the schema in code. @qtbhappy

**Comment by pjcpjc** [comment]
Ahh, you want `sqlacodegen` except for `ticdat`?  I don't see a lot of value in something like that for data science engines, since I think there is a lot of value in the explicit declaration of the input schema so as to define the `solve` function requirements. Check out [https://github.com/ticdat/ticdat/wiki/1-Beginner-ticdat-intro](this) wiki page for my thinking here.

**Comment by qtbgo** [comment]
Thanks for your response, pjcpjc. I still think it is of great importance to have this function. When doing an optimization project, the first thing I do is to design a data model visually, for example in an MS Access DB. I build tables, relationships visually, this is a big picture which let me check all relationships conveniently. After that, I code ticdat schema manually, which is very error-prone. Then if I make a design change in DB, I need to synchronize ticdat schema manually, which is tedious. If we can generate ticdat schema automatically, we can improve this process greatly.

**Comment by pjcpjc** [comment]
To be clear, I'm glad you find ticdat helpful, particularly if you prefer the relatively simple coding up of tables/fields relative to something like SQLAlchemy. But your workflow is just too idiosyncratic to the other ticdat developers (who communicate with me internally and who inspire the other tickets you see here) for me to prioritize your request. 
I hope you understand. I'm glad to share ticdat as an open source project but Opex Analytics is the sponsor of this project and their needs are the priority. As it happens, nobody here is  designing the tables/fields using Access - we are designing the tables/fields with ticdat, and then building the schema from the ticdat code itself.
Feel free to keep asking questions however! If I was independently wealthy, I might think differently on this request.

**Comment by qtbgo** [comment]
Thank you for your reply. I take Access for just an example, in fact, I use other visual DB design tools. I like design DB visually. If I design from tidat schema, I cannot see the big picture of the relationships between tables visually.

Of course, ticDat is very cool and thank you for sharing it. This is only a wish, not a request.
