### ISSUE TITLE
feature required: Is it possible to support google ortools' sat solver?

### ISSUE THREAD

**Issue by qtbgo** [ticdat/ticdat#154]
Just wonder if it is possible to make ticdat support google ortools' sat solver just as support cplex solver?

**Comment by pjcpjc** [comment]
Hi @qtbgo  - I've gotten ticdat to work nicely with Gurobi, CPLEX and pulp, and also used for non-MIP work like `sklearn` ML tasks. I've even done a fair bit of ticdat, AMPL work (via `amplpy`). So, I don't see any reason why it wouldn't play nicely with `ortools`. 

You can see demonstrations of all the different ways I've used it in the [examples](https://github.com/ticdat/ticdat/tree/master/examples) directory.

**Comment by qtbgo** [comment]
I may not express myself clearly. Let me give an example.  To use cplex solver, we can use  mdl = docplex.mp.model.Model('diet')  . But we can not use, e.g., mdl = ortools.sat.model.Model('diet')  to use sat solver in ortools.

**Comment by pjcpjc** [comment]
@qtbgo  -- your code sample doesn't reference `ticdat` tho.... I don't know much about `ortools`. You probably know more than me. 
Sorry, I'm just not seeing a `ticdat` feature request here.

**Comment by qtbgo** [comment]
My fault. Now I understand. Thank you.

**Comment by pjcpjc** [comment]
@qtbgo happy to help
