### ISSUE TITLE
Add command line data integrity errors support

### ISSUE THREAD

**Issue by pjcpjc** [ticdat/ticdat#164]
Now that "-e" is no longer used for command line Enfame support (#157), we can use that to provide a tabular report for data integrity errors. Specifically, launching a solve like

```
python diet.py -i input.xlsx -o output.xlsx -e integrity_errors.xlsx
```

Will dump tabularized data integrity errors into intergrity_errors.xlsx  (and **not** run `solve`) if the input.xlsx data set has integrity errors. The following code snippet gives you some idea of the table schema that will be used for integrity_errors.xlsx. As you can see, it puts all the errors of the same tape (duplicates, data types, data row fails andFK fails) into a single table, and thus  intergrity_errors.xlsx will always have four tabs regardless of the number of tables in `input_schema`. This way of reporting integrity errors has the advantage of being easy to scan, since there are only four tables. Its similart to how integrity errors were actually reported in Enframe and people seemed to like that well enough.

Inspired by @astersantana request.

**Comment by astersantana** [comment]
This is awesome, @pjcpjc! Thank you so much!

**Comment by pjcpjc** [comment]
Oops forgot the code snippet. As you can see, no matter what the `input_schema`, the integrity errors are dumped into four tables.

```
_pks = {t: pks for t, (pks, dfs) in input_schema.schema().items()}
_longest_pk =  max(len(pks) for pks in _pks.values())
_fld_names = [f"PK Field {_ + 1}" for _ in range(_longest_pk)]
solution_schema = PanDatFactory(duplicate_rows=[["Table Name"] + _fld_names, []],
                                data_type_failures=[["Table Name", "Field Name"] + _fld_names, []],
                                data_row_failures=[["Table Name", "Predicate Name"] + _fld_names, []],
                                foreign_key_failures =[["Native Table", "Foreign Table", "Mapping"] + _fld_names, []])
```

**Comment by astersantana** [comment]
Hey @pjcpjc, how about the summary table? Are you planning to include that as well?

**Comment by pjcpjc** [comment]
Implemented on develop branch.
