### ISSUE TITLE
use copy instead of DataFrame.to_sql for faster PG uploads

### ISSUE THREAD

**Issue by pjcpjc** [ticdat/ticdat#185]
initial idea from [here](https://stackoverflow.com/questions/46715354/how-does-copy-work-and-why-is-it-so-much-faster-than-insert)

Bear in mind, we're probably going to just prototype it in `ticdat` and then do the real implementation in `roundoff_helper` for a variety of reasons. 

Be sure to work off a feature branch forked from the most recent develop.

**Comment by mohit-mhjn** [comment]
## Prototype of Prototype (PoP)

Create a testing psql table for experiment:
```sql
CREATE SCHEMA hollywood
CREATE TABLE hollywood.films (title text, release date, awards int, imdb_rating real);
INSERT INTO hollywood.films VALUES 
('Fast&Furious',DATE('2003-10-01'),15,4.3),
('MIB',DATE('2005-04-01'),18,4.7);
```

Now follow along in the snippet below:

```python
from sqlalchemy import create_engine
from contextlib import closing
import pandas as pd
import io

sa_engine = create_engine("postgresql+psycopg2://mohit_mhjn:megaminds@localhost/postgres")
# get the data
df = pd.read_sql("SELECT * FROM hollywood.films", sa_engine)

# Now write df back to db  
# Assuming usual operation for roundoff solve: [truncate then insert] >>

# Current Method of pgtd is as follows:
df.to_sql('films', sa_engine, 'hollywood', if_exists='truncate', index=False)

# Proposed Method for pgtd is as follows:
buffer = io.StringIO()
df.to_csv(buffer, index=False, header=False)
buffer.seek(0)

# Truncate and copy in the same transaction - use context managers for cur and conn
with closing(sa_engine.raw_connection()) as conn:
    with closing(conn.cursor()) as cur:
        cur.execute('TRUNCATE hollywood.films')
        cur.execute("SET search_path = hollywood")
        cur.copy_from(buffer, "films", sep=',', null='')
        conn.commit()

buffer.close()
```

For actual prototype:
- This needs to be tested for nulls, exhaustive dtypes, commas in text/varchar,   
- This should handle case-sensitive names
- This should borrow tablename, engine and schema etc. from the `PostgresTicFactory` instance
- Handle `truncate`/`delete`/`fail` modes

**Comment by pjcpjc** [comment]
Closing this since it seems unlikely to be needed anytime soon. We're not seeing performance problems in this area on Foresta. I'll reopen as needed.
