### ISSUE TITLE
string data type default value

### ISSUE THREAD

**Issue by quantcn** [ticdat/ticdat#210]
Hello, 
I have a table as follows, where skillId is string:
FixedAssignment=[['employeeId', 'workDate'], ['skillId']]

I read a json data file, in the json, it doesnt supply skillId field, see:

    "FixedAssignment": [
        {
            "employeeId": "82115fb0-9690-4fa2-a6f9-97cee521ce42",
            "workDate": 3

        },

Then ticdat seems to give default value 0 to skillId in this case.
I want it gives ""  or None to skillId. 
How?

**Comment by pjcpjc** [comment]
Sorry for delayed response @quantcn

Use `TicDatFactory.set_default_value` or `PanDatFactory.set_default_value`.
