### ISSUE TITLE
field data type to be set type?

### ISSUE THREAD

**Issue by temph2020** [ticdat/ticdat#213]
Could you add a feature that allows table field types to be of a set type?

**Comment by pjcpjc** [comment]
I don't understand the request, but also, I'm disinclined to change anything in `set_data_type`. It does a good job of supporting ints, floats, strings, and date/time right now.

**Comment by pjcpjc** [comment]
You can just use row predicates for that.

**Comment by temph2020** [comment]
Sorry, based on my understanding, row predicates are meant to constrain the relationships between fields, which doesn’t seem to achieve my goal. I have added some more content above, hoping that I have made myself clear.

**Comment by pjcpjc** [comment]
Row predicates are used to apply validation rules that are too sophisticated for the rules that are configured by `set_data_type`. There is no obligation for a row predicate to compare different fields, that's just a common usage.

**Comment by temph2020** [comment]
I’m not sure if I understood you correctly. I’m not talking about data validation, but rather whether the field content can contain Python lists.
Here is another example: The following two tables, Employee and EmployeeSkill, have a parent-child relationship. 
![image](https://github.com/user-attachments/assets/569866ef-8310-43b8-b6dd-8ce818a1ac43)


If the field content supports lists, it can be simplified to a single table as shown below.
![image](https://github.com/user-attachments/assets/a8742249-8037-4a44-b21a-8dc5bca29a16)

**Comment by pjcpjc** [comment]
I believe I understood the question the first time. It's very similar to a couple of apps we have on Foresta, and we use row predicates. 

If you want more detailed support, you can hire one of our Python / `ticdat` experts at [Decision Spot](https://www.decisionspot.com/contact-us).  

Regardless, best wishes.

**Comment by temph2020** [comment]
My Apologies.

1. I used a JSON file to generate a .dat file, and it is actually possible to store a list in a field. 
dat = JsonTicFactory(input_schema).create_tic_dat(myjson)
2. The problem occurs when I try to write to Excel using input_schema.xls.write_file(dat, ‘input.xlsx’, allow_overwrite=True).
it throws an error:
    raise TypeError("Unsupported type %s in write()" % type(token))
TypeError: Unsupported type <class 'list'> in write()
This looks like an issue with the xlsxwriter library.

**Comment by pjcpjc** [comment]
To repeat, we at DS are doing exactly this and not seeing bugs, to include when the data is serialized into Excel or CSV. I just can't reveal all the fancy tricks for free.
