### ISSUE TITLE
Migrate ticdat to-do list

### ISSUE THREAD

**Issue by snelson3** [ticdat/ticdat#4]
_From @pjcpjc on March 7, 2019 3:20_

Stuff I can do after Sam has migrated repo.

 * "opalytics" removed from all the .py files.
   * `opalytics.py` removed wholesale. (It's a thin layer on top of `pandas` support...  if needed later I can recreate easily)
 * `setup.py`
   * remove python 2X support
   * change emails away from accenture
 * General cleaning of README.md
 * review of wiki content

_Copied from original issue: opalytics/opalytics-ticdat#218_

**Comment by pjcpjc** [comment]
looks good
