### ISSUE TITLE
compound foreign keys not labeling correctly

### ISSUE THREAD

**Issue by snelson3** [ticdat/ticdat#5]
The assumption that a compound foreign key is X-to-many iff the foreign fields do not constitute the foreign primary key is false. Really, the relationship is X-to-one if the foreign fields are a super-set of the foreign primary key. The relationship is one-to-X if the native fields are a super-set of the primary key.

**Comment by pjcpjc** [comment]
This was the old issue #196.

**Comment by pjcpjc** [comment]
This was fixed a while ago apparently.
